from typing import List, Dict, Any


# =========================================================
# Canonical Entity Labels
# =========================================================

TYPE_MAP = {

    # DeBERTa
    "NAME": "NAME",
    "ADDRESS": "ADDRESS",
    "DOB": "DOB",
    "PAN": "PAN",
    "AADHAAR": "AADHAAR",
    "PHONE": "PHONE",
    "EMAIL": "EMAIL",
    "DRIVING_LICENCE": "DRIVING_LICENCE",
    "VOTER_ID": "VOTER_ID",

    # Regex
    "Name": "NAME",
    "Address": "ADDRESS",
    "Date of Birth": "DOB",
    "PAN": "PAN",
    "Aadhaar": "AADHAAR",
    "Phone": "PHONE",
    "Email": "EMAIL",
    "Driving Licence": "DRIVING_LICENCE",
    "Voter ID": "VOTER_ID"
}


# =========================================================
# Entity Type Normalization
# =========================================================

def normalize_entity_type(
    entity_type: str
) -> str:

    if not entity_type:
        return ""

    entity_type = str(entity_type).strip()

    return TYPE_MAP.get(
        entity_type,
        entity_type.upper().replace(" ", "_")
    )


# =========================================================
# Value Normalization
# =========================================================

def normalize_entity_value(
    entity_type: str,
    value: str
) -> str:

    if value is None:
        return ""

    value = str(value).strip()

    if not value:
        return ""

    entity_type = normalize_entity_type(
        entity_type
    )

    # Remove accidental whitespace around
    # punctuation generated by tokenization.
    value = " ".join(
        value.split()
    )

    if entity_type in {
        "PAN",
        "AADHAAR",
        "PHONE",
        "DRIVING_LICENCE",
        "VOTER_ID"
    }:

        # These identifiers should not contain
        # tokenization whitespace or separators.
        if entity_type in {
            "AADHAAR",
            "PHONE",
            "DRIVING_LICENCE"
        }:
            value = value.replace(
                " ",
                ""
            )

    if entity_type in {
        "PAN",
        "VOTER_ID"
    }:
        value = value.upper()

    # DeBERTa may return punctuation attached to
    # an address fragment.
    if entity_type == "ADDRESS":
        value = value.strip(
            " \t\r\n,;:"
        )

    return value


# =========================================================
# Single Entity
# =========================================================

def normalize_entity(
    entity: Dict[str, Any]
) -> Dict[str, Any]:

    # Support both formats:
    #
    # Regex:
    # {
    #   "type": "...",
    #   "value": "..."
    # }
    #
    # DeBERTa:
    # {
    #   "entity": "...",
    #   "text": "..."
    # }

    entity_type = entity.get(
        "type"
    )

    if not entity_type:
        entity_type = entity.get(
            "entity",
            ""
        )

    value = entity.get(
        "value"
    )

    if value is None:
        value = entity.get(
            "text",
            ""
        )

    normalized_type = normalize_entity_type(
        entity_type
    )

    normalized_value = normalize_entity_value(
        normalized_type,
        value
    )

    normalized = {
        "type": normalized_type,
        "value": normalized_value,
        "confidence": float(
            entity.get(
                "confidence",
                0.0
            )
        ),
        "source": entity.get(
            "source",
            "unknown"
        )
    }

    if "start" in entity:
        normalized["start"] = entity["start"]

    if "end" in entity:
        normalized["end"] = entity["end"]

    if "validated" in entity:
        normalized["validated"] = entity[
            "validated"
        ]

    return normalized


# =========================================================
# Multiple Entities
# =========================================================

def normalize_entities(
    entities: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:

    normalized = []

    for entity in entities:

        item = normalize_entity(
            entity
        )

        if not item["type"]:
            continue

        if not item["value"]:
            continue

        normalized.append(
            item
        )

    return normalized